### ISSUE TITLE
erorr

### ISSUE THREAD

**Issue by MGTV01** [vanhbakaa/Cexio-Tap-bot#1]
![image](https://github.com/user-attachments/assets/bda66ce3-5e89-4621-853b-cf2300607046)
Hello engineer, this error is encountered during execution

**Comment by vanhbakaa** [comment]
fixed set AUTO_CLAIM_SQUAD_BONUS to False to fix it

**Comment by MGTV01** [comment]
> fixed set AUTO_CLAIM_SQUAD_BONUS to False to fix it

It's great
