### ISSUE TITLE
Fix and Sync Taps

### ISSUE THREAD

**Issue by AlexanderQueen** [vanhbakaa/Cexio-Tap-bot#11]
Pls, adjust the taps to be able to send the wanted amount you specify in .env and sync them with game cuz in game the amount is not changing.

**Comment by vanhbakaa** [comment]
yes it already have u can check in config 
![image](https://github.com/user-attachments/assets/734415eb-8734-4f69-a99d-a8f2dd2c5dd1)

**Comment by vanhbakaa** [comment]
dont try to put the tap to high you can get banned as well

**Comment by AlexanderQueen** [comment]
You have 1k taps available, i want to click 1k and wait 5-6 minutes. That's the logic, or we flood them with requests with each 25,75 taps...
