### ISSUE TITLE
Alwayes After Open Bot In Telegram

### ISSUE THREAD

**Issue by Pawansingh333** [vanhbakaa/Cexio-Tap-bot#12]
Tap failed - please stop the code and open the bot in telegram then tap 1-2 times and run this code again. it should be worked!

**Comment by DenisItStep** [comment]
Clicked the bot button, after shutting down and restarting the same error pops up.
What can I do if I have a large farm? Not everywhere it is possible to start telegram and click the button.

**Comment by vanhbakaa** [comment]
disable auto_tap u can just claim btc from cexp power
