### ISSUE TITLE
How to use multiple accounts؟

### ISSUE THREAD

**Issue by vahidghadim** [vanhbakaa/Cexio-Tap-bot#16]
I want to use multiple accounts in the robot. Can you guide me?

**Comment by AetherVoyager** [comment]
Just add new sessions

**Comment by MrTimonM** [comment]
> Just add new sessions

What about API_ID and API_HASH?

**Comment by AetherVoyager** [comment]
no issue you can use same API_ID and API_Hash

**Comment by vanhbakaa** [comment]
> that means, I just need to add multiple sessions in the session folder? And, I can use any API_ID and Hash i want?

you just need 1 api_id/api_hash to create sessions
