### ISSUE TITLE
Tap failed - please stop the code and open the bot in telegram then tap 1-2 times and run this code again. it should be worked!

### ISSUE THREAD

**Issue by ngocbae98** [vanhbakaa/Cexio-Tap-bot#23]
2024-09-10 08:38:27 | ERROR    | 208 - bae |  Tap failed - please stop the code and open the bot in telegram then tap 1-2 times and run this code again. it should be worked!

**Comment by vanhbakaa** [comment]
Turn off auto tao

**Comment by prognt** [comment]
```
                if settings.AUTO_TAP:
                    await self.tap(http_client, authToken, 0)
                    await asyncio.sleep(randint(settings.SLEEP_BETWEEN_TAPS[0], settings.SLEEP_BETWEEN_TAPS[1]))

                    while runtime > 0:
```
works for me, add zero tap before real taps

**Comment by ngocbae98** [comment]
> ```
>                 if settings.AUTO_TAP:
>                     await self.tap(http_client, authToken, 0)
>                     await asyncio.sleep(randint(settings.SLEEP_BETWEEN_TAPS[0], settings.SLEEP_BETWEEN_TAPS[1]))
> 
>                     while runtime > 0:
> ```
> 
> works for me, add zero tap before real taps

thanks for your tip, i will try pro

**Comment by ngocbae98** [comment]
> Turn off auto tao

your bad idea

**Comment by prognt** [comment]
wait for author make update @vanhbakaa

**Comment by ngocbae98** [comment]
> wait for author make update @vanhbakaa

you can't update code on github?

**Comment by prognt** [comment]
> > wait for author make update @vanhbakaa
> 
> you can't update code on github?

in this repository - no. wait for author

**Comment by vanhbakaa** [comment]
> > wait for author make update @vanhbakaa
> 
> you can't update code on github?

Updated
