### ISSUE TITLE
443 error

### ISSUE THREAD

**Issue by hdmjdp** [vanhbakaa/Cexio-Tap-bot#24]

**Comment by devillom** [comment]
2024-09-11 18:00:50 | INFO     | 562 - Minimum energy reached: 199
{'status': 'error', 'data': {'reason': 'Invalid params, fast taps'}}
2024-09-11 18:00:50 | ERROR    | 219 - web |  Tap failed - response code: 401

**Comment by vanhbakaa** [comment]
> 2024-09-11 18:00:50 | INFO | 562 - Minimum energy reached: 199 {'status': 'error', 'data': {'reason': 'Invalid params, fast taps'}} 2024-09-11 18:00:50 | ERROR | 219 - web | Tap failed - response code: 401

dont worrie if it just show up 1 time
