### ISSUE TITLE
the bot stopped running

### ISSUE THREAD

**Issue by wmzaru** [vanhbakaa/Cexio-Tap-bot#25]
After the update on September 8 bot stopped running, updates did not help, installed the bot again, the same error.
![cex](https://github.com/user-attachments/assets/f268da8f-513a-4b51-bce4-c1c4afe95697)

**Comment by wmzaru** [comment]
Last update, the error has not changed

**Comment by vanhbakaa** [comment]
Update your api hash and api id in .env file
