### ISSUE TITLE
buy cards

### ISSUE THREAD

**Issue by OS-VRU** [vanhbakaa/Cexio-Tap-bot#30]
as i see , if you add some session esp. more than 1 session, bot only buys cards for 1 of them. it doesn't buy for another session.

**Comment by OS-VRU** [comment]
also bot buys cards so fast , isn't it better to add some delay for buying cards?

**Comment by vanhbakaa** [comment]
> also bot buys cards so fast , isn't it better to add some delay for buying cards?

added
