### ISSUE TITLE
Auto-Upgrade malfunction

### ISSUE THREAD

**Issue by zkiller30000** [vanhbakaa/Cexio-Tap-bot#38]
It stopped auto upgrading even when it's on True in config and .env. I tried to fully reinstall, doesn't work.

**Comment by vanhbakaa** [comment]
> It stopped auto upgrading even when it's on True in config and .env. I tried to fully reinstall, doesn't work.

do show me your full setting

**Comment by zkiller30000** [comment]
It was because of waiting for the most profitable card.
