### ISSUE TITLE
File not found error

### ISSUE THREAD

**Issue by bootfast** [vanhbakaa/Cexio-Tap-bot#45]
![Screenshot_2024-10-10-21-37-09-261_com termux](https://github.com/user-attachments/assets/66060231-dd39-4896-adb0-0acdfc178e4b)

**Comment by vanhbakaa** [comment]
Try to restart the bot

**Comment by bootfast** [comment]
> Try to restart the bot

problem persists..

**Comment by bootfast** [comment]
Thanks for the update, fixed now
