### ISSUE TITLE
Vps

### ISSUE THREAD

**Issue by mMdooD** [vanhbakaa/Cexio-Tap-bot#50]
Hi bro i have a problem with the script in vps it gives me an error about certificate: 
![IMG_20241017_225651](https://github.com/user-attachments/assets/1df14159-c264-45e7-8c80-fd9b97f3c4bd)
Pls give me a hint 
and tnx

**Comment by vanhbakaa** [comment]
https://support.securly.com/hc/en-us/articles/360026808753-How-do-I-manually-install-the-Securly-SSL-certificate-on-Windows

here install  a certificate for your window same as this tutorial

**Comment by mMdooD** [comment]
Tnx but didn't work
