### ISSUE TITLE
Where I can get those     =        API_ID=572298785 API_HASH=

### ISSUE THREAD

**Issue by Nwazit** [vanhbakaa/Cexio-Tap-bot#51]
Where I can get those     =        API_ID=572298785 API_HASH=

**Comment by Bakhtafarid1** [comment]
1.Go to [my.telegram.org](https://my.telegram.org/) and log in using your phone number.
2.Select "API development tools" and fill out the form to register a new application.
3.Note down the API_ID and API_HASH in .env file provided after registering your application.

**Comment by Nwazit** [comment]
yes I get it but i have another problem inside the envirment. can y show me your seetings

**Comment by Nwazit** [comment]
Thanks buddy
