### ISSUE TITLE
error while getting user data. Reponse 401. Try again after 30s

### ISSUE THREAD

**Issue by parafius** [vanhbakaa/Cexio-Tap-bot#52]
![image](https://github.com/user-attachments/assets/668e44b8-454d-4906-9f95-32312eba0aed)
all sessions have this error, the sessions are fine

**Comment by bootfast** [comment]
Everyone using scripts, cex banned them.. happy farming

**Comment by vanhbakaa** [comment]
Join my tg channel for more info
