### ISSUE TITLE
Can you make version for query?

### ISSUE THREAD

**Issue by Khebotz** [vanhbakaa/Cexio-Tap-bot#6]
I cant use Api has-id cause there more risky than query. Can build this for query too?

**Comment by vanhbakaa** [comment]
But it refresh after a while so you need to get it again

**Comment by Khebotz** [comment]
> But it will refresh after a while so you need to get it again

If refresh everyday its okey. If you can, put this version too^^

**Comment by vanhbakaa** [comment]
No it refresh every hour
