### ISSUE TITLE
Error while getting user data. Response 401. Try again after 30s

### ISSUE THREAD

**Issue by Inquisitor007** [vanhbakaa/Cexio-Tap-bot#61]
latest update

48|CEXIO  | 2024-11-14 03:00:42 | ERROR    | 208 - Error while getting user data. Response 401. Try again after 30s
48|CEXIO  | 2024-11-14 03:01:12 | ERROR    | 437 - 9242424 | Error code 401 While trying to get data
48|CEXIO  | 2024-11-14 03:01:12 | WARNING  | 232 - 9242424 | Failed to get special tasks data. Response code: 401
48|CEXIO  | 2024-11-14 03:01:12 | INFO     | 662 - 9242424 | No special tasks now!
48|CEXIO  | 2024-11-14 03:01:12 | ERROR    | 458 - 9242424 | Error code 401 While trying to get completed task
48|CEXIO  | Traceback (most recent call last):
48|CEXIO  |   File "/CEXIO/bot/core/tapper.py", line 664, in run
48|CEXIO  |     for task in self.task:
48|CEXIO  | TypeError: 'NoneType' object is not iterable
48|CEXIO  | 2024-11-14 03:01:12 | ERROR    | 742 - 9242424 | Unknown error: 'NoneType' object is not iterable

**Comment by vanhbakaa** [comment]
banned
